print('[Bernie] Starting Tunings module')

-- Recipes
env.AddRecipe2("piggyback", { GLOBAL.Ingredient("pigskin", 6), GLOBAL.Ingredient("silk", 6), GLOBAL.Ingredient("rope", 4) }, GLOBAL.TECH.SCIENCE_TWO)
env.AddRecipe2("compass", { GLOBAL.Ingredient("goldnugget", 1), GLOBAL.Ingredient("marble", 1) }, GLOBAL.TECH.SCIENCE_TWO)
env.AddRecipe2("fence_rotator", { GLOBAL.Ingredient("spear", 1), GLOBAL.Ingredient("marble", 2), GLOBAL.Ingredient("rope", 1) })
env.AddRecipe2("wathgrithr_shield", { GLOBAL.Ingredient("goldnugget", 3), GLOBAL.Ingredient("beefalowool", 3) }, GLOBAL.TECH.NONE, { builder_skill = "wathgrithr_arsenal_shield_1" })

-- Lootables
local lootables = {
    walrus = { { 'meat', 1.00 }, { 'blowdart_pipe', 0.5 }, { 'walrushat', 0.50 }, { 'walrus_tusk', 0.5 }, { 'walrus_tusk', 0.5 } },
    slurtle = { { 'slurtleslime', 1.00 }, { 'slurtle_shellpieces', 0.80 }, { 'slurtleslime', 0.80 }, { 'slurtlehat', 0.30 } },
    snurtle = { { 'slurtleslime', 1.00 }, { 'slurtle_shellpieces', 0.80 }, { 'slurtleslime', 0.80 }, { 'armorsnurtleshell', 0.80 } },
    lightninggoat = { { 'meat', 1.00 }, { 'meat', 1.00 }, { 'lightninggoathorn', 0.6 }, { 'goatmilk', 0.6 } },
    chargedlightninggoat = { { 'meat', 1.00 }, { 'meat', 1.00 }, { 'lightninggoathorn', 1 }, { 'goatmilk', 1 }, { 'goatmilk', 0.6 } },
    krampus = { { 'monstermeat', 1.0 }, { 'charcoal', 1.0 }, { 'charcoal', 0.1 }, { 'steelwool', 0.1 }, { 'gears', 0.1 }, { 'livinglog', 0.1 }, { 'marble', 0.1 }, { 'krampus_sack', .01 } }
}

for prefab, loot in pairs(lootables) do
    AddPrefabPostInit(prefab, function(inst)
        GLOBAL.SetSharedLootTable(prefab, loot)
        if inst.components.lootdropper ~= nil then
            inst.components.lootdropper:SetLoot({})
            inst.components.lootdropper:SetChanceLootTable(nil)
            inst.components.lootdropper:SetChanceLootTable(prefab)
        end
    end)
end

-- Tuning
TUNING.MONKEY_TOKEN_COUNTS.LEVEL_1 = 0
TUNING.MONKEY_TOKEN_COUNTS.LEVEL_2 = 2
TUNING.MONKEY_TOKEN_COUNTS.LEVEL_3 = 3
TUNING.MONKEY_TOKEN_COUNTS.LEVEL_4 = 5
TUNING.WES_DAMAGE_MULT = 1
TUNING.WES_WORK_MULTIPLIER = 1
TUNING.BALLOON_DAMAGE = 20
TUNING.BALLOON_ATTACK_RANGE = 3
TUNING.WONKEY_WALK_SPEED_PENALTY = 1.1
TUNING.WONKEY_SPEED_BONUS = 2.5
TUNING.WONKEY_TIME_TO_RUN = 2
TUNING.WONKEY_RUN_HUNGER_RATE_MULT = 1.1
TUNING.WILLOW_LUNAR_FIRE_COOLDOWN = 16
TUNING.WX78_MIN_MOISTURE_DAMAGE = -1
TUNING.WX78_MOVESPEED_CHIPBOOSTS = { 0.00, 0.1, 0.2, 0.3 }
TUNING.WOLFGANG_SANITY_NIGHT_DRAIN = 1.5
TUNING.WOLFGANG_SANITY_NIGHT_DRAIN_SMALL = 1.25

TUNING.HAMBAT_DAMAGE = 55

TUNING.BEEFALO_HUNGER_RATE = TUNING.BEEFALO_HUNGER_RATE * 0.8
TUNING.BEEFALO_DOMESTICATION_ATTACKED_BY_PLAYER_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_ATTACKED_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_LOSE_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_ATTACKED_OBEDIENCE = 0

TUNING.OCEANTREE_STAGES_TO_SUPERTALL = 2
TUNING.SHADE_CANOPY_RANGE = 56       -- 28
TUNING.SHADE_CANOPY_RANGE_SMALL = 44 -- 22

TUNING.MAX_FIRE_DAMAGE_PER_SECOND = 160

TUNING.GRUEDAMAGE = 9999
TUNING.WALRUS_REGEN_PERIOD = TUNING.WALRUS_REGEN_PERIOD * 0.5
TUNING.BEEGUARD_HEALTH = 140
TUNING.BEEGUARD_DASH_SPEED = 7
TUNING.BEEGUARD_SPEED = 4
TUNING.LAVAE_HEALTH = 140

TUNING.SHADOW_ROOK.HIT_RANGE = 2.5
TUNING.SHADOW_KNIGHT.ATTACK_RANGE_LONG = 3
TUNING.TOADSTOOL_HEALTH = 32500
TUNING.TOADSTOOL_MUSHROOMBOMB_RADIUS = 3
TUNING.TOADSTOOL_SPOREBOMB_HIT_RANGE = 3
TUNING.TOADSTOOL_SPORECLOUD_RADIUS = 4
TUNING.TOADSTOOL_SPORECLOUD_LIFETIME = 20
TUNING.TOADSTOOL_MUSHROOMSPROUT_CHOPS = 6
TUNING.TOADSTOOL_MUSHROOMSPROUT_CD = 40
TUNING.CRABKING_CLAW_ATTACKRANGE = 3.6
TUNING.CRABKING_CLAW_BOATDAMAGE = 20
TUNING.CRABKING_GEYSER_BOATDAMAGE = 5
TUNING.CRABKING_REGEN = 25

TUNING.DEERCLOPS_HEALTH = 8000
TUNING.DEERCLOPS_ATTACK_PERIOD = 3

TUNING.DRAGONFLY_ENRAGE_DURATION = 30
TUNING.DRAGONFLY_FIRE_DAMAGE = 200
TUNING.DRAGONFLY_ATTACK_RANGE = 5
TUNING.DRAGONFLY_SPEED = 4
TUNING.DRAGONFLY_FIRE_SPEED = 5
TUNING.DRAGONFLY_HIT_RANGE = 5
TUNING.DRAGONFLY_FIRE_HIT_RANGE = 5
TUNING.BEEQUEEN_DAMAGE = 200
TUNING.BEEQUEEN_SPEED = 3
TUNING.BEEQUEEN_ATTACK_PERIOD = 2
TUNING.BEEQUEEN_ATTACK_RANGE = 5
TUNING.BEEQUEEN_HIT_RANGE = 5
TUNING.BEEQUEEN_SPAWNGUARDS_CD = { 28, 26, 24, 22 }
TUNING.BEEQUEEN_FOCUSTARGET_CD = { 120, 60, 32, 24 }
TUNING.NO_BOSS_TIME = 16

TUNING.EFFIGY_HEALTH_PENALTY = 0
TUNING.PIGGYBACK_SPEED_MULT = 1
TUNING.FISHINGROD_USES = 10
TUNING.FISHING_MINWAIT = 1
TUNING.FISHING_MAXWAIT = 10
TUNING.OCEANFISH_MIN_INTEREST_TO_BITE = 0.1
TUNING.FENCE_ROTATOR_DAMAGE = 51
TUNING.FENCE_ROTATOR_USES = 250
TUNING.WATHGRITHR_SHIELD_ARMOR = 500

TUNING.HEAT_ROCK_CARRIED_BONUS_HEAT_FACTOR = 8

TUNING.BUILD_DISTANCE = 0.6
TUNING.PVP_DAMAGE_MOD = 1

TUNING.DAY_HEAT = 12
TUNING.NIGHT_COLD = -14
TUNING.SUMMER_RAIN_TEMP = -16
TUNING.MOONROCKSHELL_CHANCE = 1
