return {
    accept = "Aceitar",
    continue = "Continuar",
    close = "Fechar",
    _return = "Retornar",
    leave = "Desconectar",

    join = {
        title = "\n\n\n\nAtenção, %player%!",
        description = "\n\nO servidor se diferencia criando cenários mais difíceis. Isso implica que o jogo foi rebalanceado para esse papel.  Também contamos com anticheats, evite visão-noturna!"
    },

    rank = {
        {
            title = "Rank: Brasil Together",
            description = {
                "Neste lugar, estão imortalizados",
                "os jogadores mais esforçados das",
                "Constantes. Levante sua lança!",
                " ",
                "1) O rank atualiza após um tempo.",
                "2) A pontuação é para ESSE lugar.",
                "3) Trapaça pode desqualificar-te.",
                "4) Jonas está banido do server 1.",
                "5) Mentira, ele não está banido.",
                "6) Rank não limpa em mapas novos.",
                " ",
                "Para mais detalhes, é aconselhado",
                "que junte-se ao server do Discord",
                "do Brasil-Together!"
            }
        },
        {
            title = "Rank: Pontos",
            description = {
                "Aqui estão os jogadores com maior",
                "acúmulo de pontos. Quais competem",
                "por reconhecimento e torradas.",
                " ",
            }
        },
        {
            title = "Rank: Oinks",
            description = {
                "Aqui estão os jogadores com maior",
                "acúmulo de Oinks, economize para",
                "comprar porcarias inúteis.",
                " ",
            }
        },
    },

    guidebook = {
        {
            title = "Guia: Brasil Together",
            description = {
                "O que te traz ao Brasil-Together?",
                "Bem, esse é seu guia de mudanças.",
                "Leia, garanto que será rapidinho.",
                " ",
                "Bem, cada página tem um objetivo.",
                "Dessa forma, você pode procurar o",
                "que deseja mais facilmente. Basta",
                "buscar o tópico que te interessa.",
                " ",
                "Não toleramos trapaças por aqui..",
                "Nesse lugar, queremos um ambiente",
                "justo e desafiador. Caso goste de",
                "mods de Zoom, Visão-Noturna, etc,",
                "orientamos que busque outro lugar",
                "para jogar. Dessa forma, você não",
                "se estressa com limitações.",
            }
        },
        {
            title = "Guia: Mundo",
            description = {
                "Aqui você irá receber informações",
                "de como o mundo se comporta. Como",
                "o Constant planeja agir...",
                " ",
                "Sobre a Geração:",
                "1) Gigantes voltam mais rápido.",
                "2) Figueiros nascem naturalmente.",
                "3) Rifts são bem mais frequentes.",
                " ",
                "Sobre o Clima:",
                "1) Os dias são mais quentes (+6°)",
                "2) As noites são mais frias (-6°)",
                "3) Maior variação de clima (+20%)",
                "4) Removido o limite climático...",
                " ",
                "Sobre o Narrador:",
                "1) Um narrador de eventos chegou!",
                "2) Ele vai gerar eventos incertos",
                "3) Eles não acontecem em seguida.",
                "4) Lobos podem vir te caçar hoje!",
                "5) Ou talvez um grupo de Krampus.",
                "6) Hoje pode ser um dia de calor.",
                "7) Mas também pode esfriar muito.",
                "8) As chuvas podem vir sem aviso.",
            }
        },
        {
            title = "Guia: Itens",
            description = {
                "Aqui estão as mudanças dos Itens.",
                "Alguns deles estão mais fracos...",
                "Outros estão bem mais fortes!",
                " ",
                "Sobre a Itens Comuns:",
                "1) As mochilas são desequipáveis.",
                "2) Piggyback não causa lentidão.",
                "3) Flares podem revelar seu mapa.",
                "4) Flares miráveis, mire e atire!",
                "5) Pedras Térmicas são duráveis.",
                "⬆ Elas também combam com roupas.",
                "⬆ Mas aquecem bem menos também...",
                "6) Muros recebem frações de dano.",
                "7) Fogo pode adicionar insolação.",
                " ",
                "Sobre a Itens Especiais:",
                "1) Alarming Clock melhorado.",
                "⬆ Pure Horror causa dano planar.",
                " ",
                "Sobre os Trinkets:",
                "1) Slot para Trinkets adicionado.",
                "⬆ Trinkets são itens com efeitos.",
                "2) O Compass revela seus aliados.",
                "3) Gnome/ette: Trolls de plantão.",
                "⬆ Eles causam efeitos aleatórios.",
            }
        },
        {
            title = "Guia: Gigantes",
            description = {
                "Os Gigantes são frágeis contra os",
                "sobreviventes que estão perdidos,",
                "porém bem fortes contra grupos...",
                " ",
                "Sobre as Mecânicas:",
                "1) Gigantes causam dano em todos.",
                "2) Os Prefixos podem mudar stats:",
                "⬆ O Dormant multiplica sua saúde.",
                "⬆ Defiant aumenta o dano causado.",
                "⬆ O Flying se move rapidamente...",
                "⬆ Royal repete mais habilidades.",
                "⬆ O Savage ataca em maior ritmo.",
                "3) Dragonfly não desmaia em dano.",
                "⬆ invés disso vai se incinerar...",
                "⬆ mas o enrage é menos opressor.",
                "4) O Deerclops nasce VIOLENTO.",
                "⬆ Podem Projetar lasers oculares.",
                "⬆ Velocidade de ataque aumentou.",
                "⬆ Sua vida aumentou também. (2x)",
                " ",
                "Sobre os Ajustes:",
                "1) O Toadstool possui menos vida,",
                "⬆ e os seus cogumelos também tem.",
                "2) A Beequeen ferroa mais forte.",
                "⬆ Também demora mais pra invocar.",
                "3) Crabking bate menos em barcos.",
                "7) Os Shadow Pieces estão fracos.",
                "⬆ Menos range, desviar é fácil...",
            }
        },
        {
            title = "Guia: Criaturas",
            description = {
                "Guia sobre criaturas do servidor.",
                "Parte delas mudaram apenas stats.",
                "Outras... Mudaram pra caramba...",
                " ",
                "Sobre os Aliados:",
                "1) O Beefalo NUNCA perde amizade!",
                "⬆ Adicionalmente, doma rapidinho.",
                "⬆ Mas ele distribui dano pra você",
                " ",
                "Sobre os Neutros:",
                "1) Desabrigados constroem casas:",
                "⬆ Porcos, Merms, Catcoons, etc...",
                "2) Sapos não vagam no sol do dia.",
                "3) Cabras dropam mais recursos.",
                " ",
                "Sobre os Inimigos:",
                "1) As sombras são mais perigosas.",
                "2) Charlie dá mais dano. Muuuito.",
                "3) Os Walrus podem ter 2 dentes.",
                "4) Lavaes e Beeguards mais fracas",
                "5) Lesmas podem dropar mais vezes."
            }
        },
        {
            title = "Guia: Sobreviventes",
            description = {
                "Mas sobre nossos Sobreviventes...",
                "Eles foram alterados também. Será",
                "possível deixá-los consistentes?*",
                " ",
                "Sobre o Wes:",
                "1) Wes trabalha e dá dano normal.",
                " ",
                "Sobre a Willow:",
                "1) A Willow não queima aliados...",
                "⬆ O 'fogo gentil' não causa dano!",
                "⬆ Habilidades incineram monstros.",
                "⬆ Matar traz centelhas à Willow.",
                " ",
                "Sobre o Wonkey:",
                "1) Wonkey não desacelera andando.",
                " ",
                "Sobre o Walter:",
                "1) Walter cai de Beefalos também.",
                " ",
                "Sobre a Wigfrid:",
                "1) Wigfrid causa dano em COMBOS!",
                "⬆ Seus Beefalos causam mais dano.",
                " ",
                "Sobre o Wolfgang:",
                "1) Wolfgang tem medo de sombras.",
                "⬆ Ele geralmente perde sanidade.",
                "⬆ Recebe mais dano de sombras...",
                " ",
                "Sobre o Maxwell:",
                "1) Maxwell não pode ler livros.",
                " ",
                "Sobre a Sobrevivência:",
                "1) Comidas simples mais fracas.",
                "2) Porém preparadas duram mais.",
                "3) Pescar é mais rápido e fácil.",
                " ",
                "Sobre os Revives:",
                "1) Reviver 'SEMPRE' causa debuff.",
                "⬆ Menos Meat Effigy e Touch Stone",
            }
        },
        {
            title = "Guia: Griefers",
            description = {
                "Nossa estratégia contra Griefers.",
                "Eles chegam, queimam tudo, farmam",
                "aura e vão embora. Muito radical.",
                " ",
                "1) Você pode reconstruir coisas!.",
                "⬆ Especificamente, as queimadas.",
                "2) Chester pode revigorar cinzas!",
                "⬆ Insira as cinzas no coitadinho.",
                "⬆ Ele recupera itens queimados...",
            }
        },
        {
            title = "Guia: Mecânicas",
            description = {
                "As Mecânicas autorais do server.",
                "Representam mudanças em sistemas",
                " raiz do Don't Starve Together.",
                " ",
                "1) Dano dinâmico contra Bosses:",
                "⬆ Acontece quando você está só.",
                "⬆ Para evitar batalha demorada.",
                "2) Gelo causa DANO adicional...",
                "⬆ Escolha a vítima e a congele:",
                "⬆ Bater no gelo causa mais dano.",
                "3) Calor/frio/fome enfraquecem:",
                "⬆ Você causa menos dano fixo...",
                "⬆ Você leva dano fixo adicional.",
            }
        }
    }
}
