return {
    gnomeacidjokes = {
        "I'm a gnome, and you've been GNOMED",
        "You absolute gnoblin.",
        "Your beard lacks spiritual moisture.",
        "I've seen cave moss with greater wisdom.",
        "You smell like steamed goblin ankles.",
        "The council of tiny wizards rejects you.",
        "Your gnome license has been revoked.",
        "You dance like a concussed mole.",
        "The mushrooms whisper insults about you.",
        "You malformed garden creature.",
        "I've buried smarter beings than you.",
        "Your aura tastes like damp bread.",
        "You fight like a frightened acorn.",
        "The dirt refuses to remember your footsteps.",
        "You have the posture of expired yogurt.",
        "A raccoon shaman cursed your bloodline.",
        "You look heavily chewable.",
        "Your thoughts arrive in alphabetical order.",
        "The frogs voted against your existence.",
        "You gnasty little compost goblin.",
        "Even the worms feel secondhand embarrassment.",
        "Your bones jiggle with dishonor.",
        "You have peasant knees.",
        "The moon called you cringe.",
        "You scream like decorative furniture.",
        "You tiny toe-eyed swamp elf.",
        "The forest keeps changing paths to avoid you.",
        "Your soul squeaks when you walk.",
        "I've farted with greater authority.",
        "The ancient gnomes would punt you downhill.",
        "You smell politically unstable.",
        "Your head contains mostly soup vapors.",
        "You emotionally overcooked turnip.",
        "A beetle could defeat you in combat.",
        "Your ancestors were probably decorative.",
        "The goblins use your name as a warning.",
        "You cursed lawn ornament.",
        "The crows ranked you lowest in charisma.",
        "You have powerful divorced mushroom energy.",
        "You are spiritually unemployed.",
        "The rocks pretend not to know you."
    },

    pignames = {
        "Pigloom",
        "Laybeef",
        "Adrenapig",
        "Jonas-Jonas",
        "Sheikoink",
        "Eddlet",
        "Pythoast"
    },

    gnomenames = {
        "Chomkys",
        "Romeu",
        "Gnaldinho",
        "Gnomeu",
        "Luis Lula Gnomacio",
        "Sir Gnomes",
        "Pedrôgnomo",
        "Gnomelindo",
        "Tonho do Caminhão",
        "Bartognome",
        "Naldão da Silva",
        "Gnomario"
    },

    gnomettenames = {
        "Doris",
        "Julietta",
        "Gnomelina",
        "Rosgnome",
        "Clarice Lisgnomector",
        "Anastácia Maranhão",
        "Maribel-bel",
        "Lucinda Cogumelo",
        "Valentina",
        "Evelygnome",
        "Bianca de Veludo",
        "Catarignome"
    }
}
