return {
    cooldown = 30, -- minutes
    pool = {
        "Quer acesso ao código fonte? github.com/nectaroads/Bernie-DST",
        "Junte-se ao nosso servidor Discord! discord.gg/37yfuWjyj7",
        "Junte-se ao nosso servidor Discord! discord.gg/37yfuWjyj7",
        "Junte-se ao nosso servidor Discord! discord.gg/37yfuWjyj7",
        "Cuidado! Beefalos distribuem dano para quem está acima dele.",
        "Beefalos não perdem obediência ao serem atacados, que conveniente!",
        "Walter não consegue manter equilíbrio em Beefalos.",
        "Mochilas podem ser colocadas em seu inventário!",
        "Você enfraquece quando sente frio, calor ou fome...",
        "Pedras térmicas são protegidas pelo calor de suas roupas.",
        "Cthullu ataca o jogador mais próximo dele.",
        "Você desbloqueia a Skill-tree automaticamente!",
        "Estar próximo de fogueiras faz você gastar menos energia.",
        "Aliados não atacam sobreviventes, muito menos comem comida do chão!",
        "Pets ficam mais fortes quando usam capacete, MUITO mais fortes!",
        "Marmore demora menos para crescer...",
        "Players são comestíveis... yum!",
        "Qualquer coisa congelada recebe dano extra!",
        "Os gigantes se comportam diferente, tome cuidado!",
        "Cuidado, a escuridão está mais violenta!",
        "Porcos podem construir uma casa nova após um tempo desabrigados!",
        "Você pode recuperar estruturas queimadas, basta clicar nelas.",
        "O mundo pode ter eventos aleatórios, alguns dificultam sua vida, outros nem tanto.",
        "Mochila de porquinho não te dá debuff de velocidade!",
        "Alguns porcos possuem nomes especiais de jogadores...",
        "Jogadores isolados causam mais dano em gigantes.",
        "Atacar rápido demais pode te deixar cansado.",
        "Griefing é sempre detectado, cuidado ao cometer crimes!",
        "Flares revelam parte do mapa para seus aliados.",
        "Beefalos não perdem amizade quando golpeados por sobreviventes.",
        "Você pode mirar Flares usando seu mapa, assim pode compartilhar localizações.",
        "Você sabia? Chester pode comer cinzas e transformar em itens queimados previamente.",
        "Gnomos costumam fugir das mãos dos sobreviventes...",
        "Compass é infinito, e ele revela a localização de todo mundo!",
        "Slot de Trinket é para brinquedos especiais, como o Compass.",
        "Você pode queimar ferramentas na fogueira, livre-se de porcarias da base.",
        "Wanda pode penetrar Armadura-Planar usando Pure Horror!",
        "Alimente Chester com cinzas para recuperar itens queimados.",
        "Aperte F1 e leia o Guia Brasil-Together!",
        "Aperte F1 e leia o Guia Brasil-Together!",
        "Aperte F1 e leia o Guia Brasil-Together!",
        "Wonkey não é fraco como de costume, vale a pena experimentar!",
        "Aperte F2 e descubra o Rank Brasil-Together!",
        "Beefalos bem alimentados são domados mais facilmente.",
        "Chapéu de Beefalo te ajuda a domar seu companheiro!",
        "Rifts são mais frequentes por aqui...",
        "Bosses sempre nascem com qualidades aleatórias, então tenha cautela.",
        "Itens quentes te esquentam. Itens gelados ou sombrios te esfriam.",
        "Suas roupas protegem sua pedra térmica do ambiente.",
        "Alimentos crus te alimentam menos, mas pratos costumam durar mais.",
        "Cabras, Lesmas, Walrus, etc possuem drops mais previsíveis!",
        "Sabia que um figueiro pode crescer no bioma de mandrágoras?",
        "Krampus podem carregar tesouros adicionais.",
        "Wickerbottom NUNCA esquece das coisas que aprendeu.",
        "Escudos, Rapieiras e Espadas de Madeira podem defender ataques!",
        "Todas as armaduras, roupas e armas foram rebalanceadas."
    }
}
